<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MengfeifeideMac-Mini.local" name="AiXuePaiForIOS" tests="4" failures="2" timestamp="17 May 2017 04:51:14 GMT" time="0.054" errors="0">
  <testcase name="testAssert1" time="0.011" classname="util.Test15"/>
  <testcase name="testAssert1" time="0.001" classname="util.Test15">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at util.Test15.testAssert1(Test15.java:21)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAssert1 -->
  <testcase name="testAssert1" time="0.0" classname="util.Test15">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
	at util.Test15.testAssert1(Test15.java:21)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testAssert1 -->
  <testcase name="testAssert2" time="0.0" classname="util.Test15"/>
</testsuite> <!-- AiXuePaiForIOS -->
